### ISSUE TITLE
La base de datos se pisa siempre poruqe esta en el init

### ISSUE THREAD

**Issue by eduzen** [Ambro17/TwitterBot#1]
Falta una valida os.path.exists para chequear que la base no exista previamente. 
que opinas @Ambro17 ?

**Comment by Ambro17** [comment]
El código está comentado. Coincido que no es una forma elegante de resolverlo. Pienso cambiarlo a un flag con una condicion de crear_db seteada a False por default.

Acepto más sugerencias!
